# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='users',
        ),
    ]
